### ISSUE TITLE
No bindings for 'video'

### ISSUE THREAD

**Issue by stuaxo** [mickbeaver/sdl2-cffi#1]
I was trying to port this example of modern opengl, but there are no bindings for 'video'

https://gist.github.com/binarycrusader/5823716a1da5f0273504

**Comment by mickbeaver** [comment]
Hello Stuart,

The most popular SDL2 bindings for Common Lisp can be found here:
https://github.com/lispgames/cl-sdl2

Are you familiar with the original SDL2 library in C? The Python
sdl2.video module is just that author's decision on how to organize
his Python library.

Good luck with your Common Lisp work!

**Comment by stuaxo** [comment]
Oops !   Just reported this on the wrong project... I might do some CL one day but think I was aiming for pysdl2-cffi :)
